.github/CODEOWNERS
README.md

The initial approvers/maintainers were seed from the Collector
contributors/approvers/maintainers.

Add initial approvers/maintainers to README.md and CODEOWNERS

---

server/server.go
server/types/callbacks.go
server/types/connection.go

Contributes to https://github.com/open-telemetry/opamp-go/issues/16
This is similar to what we did for the Client: it introduces an interface
which can be implemented by the actual implementation later.

Add initial Server interface and types

---

client/clientimpl.go
client/noplogger.go
internal/noplogger.go
makefile
server/connection.go
server/internal/callbacks.go
server/server.go
server/serverimpl.go
server/serverimpl_test.go

Contributes to https://github.com/open-telemetry/opamp-go/issues/32
This implements the OpAMPServer interface and adds some basic tests
to verify the functionality.
Also added ListenPath to server StartSettings since it is necessary
to implement the server.
TODO:
- Handle closing and waiting for existing connections.
- Wait for listening in Start().
- Decide what to do with OnDisconnect callback.

Begin basic server implementation

---

server/internal/callbacks.go
server/types/callbacks.go

"Disconnect" is just a regular message type under AgentToServer message
which can be handled via OnMessage just like all other message. There is
no reason OnDisconnect needs to exit.

Delete unnecessary OnDisconnect

---

server/serverimpl.go
server/serverimpl_test.go

This is a requirement of the OpAMPServer interface
which wasn't implemented initially. It should work
correcly now.
Contriubtes to https://github.com/open-telemetry/opamp-go/issues/32

Wait in Start() until server starts listening

---

client/clientimpl_test.go

This fixes the case when Stop returns without an error since
it manages to stop before the external context cancellation
is effective.

Fix client test case

---

client/callbacks.go
client/clientimpl_test.go
client/internal/receiver.go
client/types/callbacks.go
internal/examples/agent/agent/agent.go

This change implements the following OpAMP Spec requirement
https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#status-reporting:
When the Agent receives a ServerToAgent message the Agent MUST NOT
send a status report unless processing of the message received from
the Server resulted in actual change of the Agent status (e.g. the
configuration of the Agent has changed).
Before this implementation the agent would unnecessarily send status
updates even though they were unnecessary since nothing was changed.

Avoid sending status update if the effective config is unchanged

---

internal/examples/server/opampsrv/opampsrv.go
server/callbacks.go
server/httpconnection.go
server/httpconnectioncontext.go
server/serverimpl.go
server/serverimpl_test.go
server/types/callbacks.go
server/types/connection.go
server/wsconnection.go

This adds plain HTTP request support to OpAMPServer implementation.
Implements spec change: https://github.com/open-telemetry/opamp-spec/pull/70

Implement plain HTTP Transport in OpAMPServer

---

client/clientimpl.go
client/clientimpl_test.go

Resolves: https://github.com/open-telemetry/opamp-go/issues/55
This PR ensures that the client includes AgentDescription every time it connects to the server, not just after `client.Start`.
Current behavior:
- Clients connection to server is interrupted.
- Client reconnects.
- Client does not prepare a "first status message" with an `AgentDescription`.
Expected behavior:
- Clients connection to server is interrupted.
- Client reconnects.
- Client prepares and sends a status including AgentDescription.

Ensure client includes AgentDescription on Reconnect

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/httpclient_test.go
client/internal/httplooper.go
client/internal/mockserver.go
client/internal/nextmessage.go
client/internal/receivedprocessor.go
client/internal/wsreceiver.go
client/internal/wsreceiver_test.go
client/internal/wssender.go
client/wsclient.go
client/wsclient_test.go
internal/examples/agent/agent/agent.go
internal/retryafter.go

- Added httpClient implementation of OpAMP client.
- Renamed client to wsClient to indicates it is a WebSocket client.
- Split Receiver into wsReceiver that contains WebSocket specific code and
receiveProcessor that contains transport-agnostic code and used by HTTP transport
implementation too.
- Adjusted most existing client tests to run twice: once for wsClient and once
for httpClient.
- Added a couple transport specific tests to httpclient_test.go and wsclient_test.go.

Implement plain HTTP Transport in OpAMPClient

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/httpclient_test.go
client/internal/clientcommon.go
client/internal/httpsender.go
client/internal/sender.go
client/internal/wssender.go
client/types/startsettings.go
client/wsclient.go
client/wsclient_test.go
internal/examples/agent/agent/agent.go

- There are no changes in functionality. Tests are not touched (except package
renaming).
- The OpAMP client logic that is common between WebSocket and plain HTTP
transports is now implemented in one place: ClientCommon struct.
- Renamed HTTPLooper to HTTPSender to have more consistent naming (we have WSSender).
- StartSettings moved to types package (forced change to avoid dependency loop).

Refactor to deduplicate common client functionality

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/internal/clientcommon.go
client/internal/clientstate.go
client/types/startsettings.go
client/wsclient.go
internal/examples/agent/agent/agent.go
internal/examples/server/data/agent.go

We don't need 2 ways to set AgentDescription, it is confusing.
Now the only way is to call SetAgentDescription(), which must be
called before Start() and may be called after Start() too.
Resolves https://github.com/open-telemetry/opamp-go/issues/47

Eliminate StartSettings.AgentDescription

---

client/clientimpl_test.go
client/httpclient.go
client/internal/clientcommon.go
client/internal/clientstate.go
client/internal/httpsender.go
client/internal/inmempackagestore.go
client/internal/mockserver.go
client/internal/packagessyncer.go
client/internal/receivedprocessor.go
client/internal/wsreceiver.go
client/internal/wsreceiver_test.go
client/types/packagessyncer.go
client/types/startsettings.go
client/wsclient.go

- This implements "Packages" spec section https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#packages-1
- TODO: increase test coverage to handle many more edge cases.
- TODO: add package usage to the example Agent/Server.

Implement package syncing

---

internal/examples/go.mod
internal/examples/supervisor/bin/.gitignore
internal/examples/supervisor/bin/supervisor.yaml
internal/examples/supervisor/main.go
internal/examples/supervisor/supervisor/commander/commander.go
internal/examples/supervisor/supervisor/config/config.go
internal/examples/supervisor/supervisor/logger.go
internal/examples/supervisor/supervisor/supervisor.go
makefile

- The Supervisor can manage OpenTelemetry Collector.
- Demonstrates basic features: applying config, configuring Collector to collect its own metrics.
TODO:
- Find a way to fetch Collector version instead of hard-coding it.
- Set instance id in the Collector config file to make sure OpAMP and Collector
metrics use the same instance id.
(Related open issue https://github.com/open-telemetry/opentelemetry-collector/issues/5398)
- Re-think callbacks to avoid unnecessary restarts
(See https://github.com/open-telemetry/opamp-go/issues/77)
- Add a way for Supervisor to understand why the Collector process exited unexpectedly.

Create simple Supervisor example

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/internal/clientcommon.go
client/internal/clientstate.go
client/internal/receivedprocessor.go
client/internal/wsreceiver_test.go
client/types/callbacks.go
client/wsclient.go
internal/examples/agent/agent/agent.go
internal/examples/supervisor/supervisor/supervisor.go
internal/proto/opamp.proto
protobufs/opamp.pb.go

Resolves https://github.com/open-telemetry/opamp-go/issues/77
We previously delivered the data received in one ServerToAgent message using
multiple callbacks. This encouraged piecemeal processing and resulted in
multiple state changes when only one would be sufficient.
The new OnMessage callback delivers all data that can affect the state at once
which makes it possible process it in one pass. In the Supervisor this allows
to restart the Agent only once when applying changes that result in config
file change.

Refactor OpAMPClient callbacks

---

README.md

Dear community, due to a transition into another role at a different organisation I am no longer able to allocate time to be an approver of OpAMP
Thank you all, it was a great pleasure to work with you and also a great opportunity to learn

Remove pmm-sumo from approvers list

---

client/httpclient.go
client/internal/clientcommon.go
client/internal/clientstate.go
client/internal/httpsender.go
client/internal/nextmessage.go
client/internal/packagessyncer.go
client/internal/sender.go
client/internal/wsreceiver.go
client/internal/wssender.go
client/types/callbacks.go
client/wsclient.go

Partially addresses #100. Also added to some internal funcs which I thought would be helpful to get a quick summary.

Update client package docs

---

client/wsclient.go

Fixes #111
Once `Stop()` is called on the websocket client we don't call `OnConnectFailed` handler if a dial fails.
Tested this fix on a system that was repeatedly showing the `OnConnectFailed` handler called during shutdown.

Don't call OnConnectFailed when failed to connect during shutdown

---

client/internal/clientcommon.go
internal/examples/server/data/agent.go

We check the omitted field and the corresponding capability bit to understand
if the compression was used.
Related to spec issue https://github.com/open-telemetry/opamp-spec/issues/109
The issue was discarded in favour of the implementation that does not
change the spec, but instead uses already existing information.

Correctly handle status compression on the server side

---

client/clientimpl_test.go
client/internal/sender.go

Implements spec change https://github.com/open-telemetry/opamp-spec/pull/116

Require that instance_uid is ULID

---

server/httpconnection.go
server/serverimpl_test.go
server/types/connection.go
server/wsconnection.go

Resolves #91 
This enables OpAMP to close the network connection to an agent from the server side

Add Disconnect() method to client connections

---

internal/retryafter.go
internal/retryafter_test.go
server/serverimpl_test.go

According to specifications, Retry-After header should be either seconds-delay or HTTP-date
https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.3
Resolves #119

Add client-side support for datetime value of Retry-After header

---

internal/examples/supervisor/supervisor/commander/commander.go
internal/examples/supervisor/supervisor/healthchecker/healthchecker.go
internal/examples/supervisor/supervisor/supervisor.go

The Supervisor now periodically polls Collector's health check endpoint and reports the health status to the OpAMP Server.

Implement health checks in Supervisor

---

client/wsclient_test.go
internal/testhelpers/tcpproxy.go
server/server.go
server/serverimpl.go
server/serverimpl_test.go

Resolves https://github.com/open-telemetry/opamp-go/issues/121

Implement Websocket server compression

---

.github/workflows/build-and-test.yml

Presumably this should help avoid failures, see https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

Use upload token with codecov to avoid failures

---

client/clientimpl_test.go
client/httpclient.go
client/internal/httpsender.go
client/internal/httpsender_test.go
client/internal/mockserver.go

In order to support HTTPs connections with certificate between Agents and Server, TLSConfig shall be passed to http.Client on HTTPSender structure.
A new function AddTLSConfig was created on httpsender.go to handle that, which is called during Start process of OPAMP httpClient.

Add TLSConfig into httpClient

---

server/server.go
server/serverimpl.go
server/serverimpl_test.go

Resolves https://github.com/open-telemetry/opamp-go/issues/152
Make sure the library-provided ConnContext function is used by the caller when they setup the HTTP Server to Attach() to, so that the context correctly stores a references to the connection. This is an internal requirement for plain http server implementation.

Change Attach signature to return ConnContext func

---

CONTRIBUTING.md
makefile

The submodule is necessary for `make gen-proto` target.
Also added a check in makefile to verify that the submodule is cloned.

Explain in CONTRIBUTING.md that opamp-spec submodule is needed

---

client/internal/httpsender.go
client/internal/httpsender_test.go

1. Client emits logs when receiving any error while trying to perform an HTTP connection to the server

Adding missing error log statement when HTTP sending fails

---

internal/examples/agent/agent/agent.go
internal/examples/supervisor/supervisor/supervisor.go

The semantic conventions define `os.type`, but the examples use `os.family`. Let's follow the convention!

Use os.type instead of os.family

---

internal/examples/supervisor/supervisor/supervisor.go
internal/examples/supervisor/supervisor/supervisor_test.go

`Supervisor.healthCheckTicker` is prepared in `(*Supervisor).startAgent`. If there is no effective config file, we will skip the call of `startAgent` causing an nil pointer dereference in the loop.

fix nil pointer dereference in supervisor example

---

server/httpconnection.go
server/serverimpl_test.go
server/types/connection.go
server/wsconnection.go

I am implementing TLS in the example server and found that I need access to the underlying net.Conn. I added Connection() method to access it. Now that we have access to net.Conn, RemoteAddr() is no longer needed, it can be substituted by Connection().RemoteAddr().
Note: this is a breaking change.

Replace Connection.RemoteAddr() by Connection()

---

client/client.go
client/clientimpl_test.go
client/internal/clientcommon.go
client/internal/httpsender.go
client/internal/httpsender_test.go
client/internal/receivedprocessor.go
client/internal/wsreceiver.go
client/internal/wsreceiver_test.go
client/wsclient.go

Calling Stop() from callbacks may result in a deadlock if the callback is called because a message is received. Stop() will wait for receiver to stop, but receiver can't stop until the callback is returned.
This change allow Stop() to initiate stopping and return without waiting for Stop() to finish.
This ability is important for implementing use cases where connection settings offer is received and the callback needs to Stop() the current OpAMP client and reconnect again using the new settings.

Fix deadlock from Stop() called from callbacks

---

client/clientimpl_test.go
client/httpclient_test.go

To avoid confusion for the people who read the tests. This commit updates the tests to use `service.*` as identifying attributes since `host.*` usually helps in understanding the host agent runs and won't necessarily be identifying attributes.

Update AgentDescription identifying attributes in tests

---

internal/examples/supervisor/bin/supervisor.yaml
internal/examples/supervisor/supervisor/supervisor.go

https://github.com/open-telemetry/opamp-go/pull/174 enabled TLS on the server and non-TLS connections are no longer accepted.
This PR updates the Supervisor to use TLS connection (with InsecureSkipVerify=true flag).

Fix supervisor example to work with TLS

---

client/httpclient.go
client/httpclient_test.go
client/types/startsettings.go

Resolves https://github.com/open-telemetry/opamp-go/issues/176

Allow setting polling interval for httpClient

---

internal/examples/server/data/agent.go
server/serverimpl.go
server/serverimpl_test.go
server/wsconnection.go

The Gorilla websocket package states that [only one concurrent write](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency) can be made to a connection at a time. The library will try to detect concurrent writes and will panic if it detects that one is happening.
We might see concurrent writes in two places:
1. If the server application doesn't guard writes when writing to an agent connection.
2. If the OpAMP server library is [responding to a message](https://github.com/open-telemetry/opamp-go/blob/146b79221c76637368e7937b50a82689733f46a2/server/serverimpl.go#L233) from the agent while the server application is also sending a message using its reference to the agent connection obtained from `OnConnectedFunc`.
In my opinion it would make sense to prevent concurrent writes …

Embed mutex in the server's websocket client

---

client/internal/httpsender.go
client/internal/httpsender_test.go

Fixes #193 
`prepareRequest` in HTTP Sender returns a `http.Request` https://github.com/open-telemetry/opamp-go/blob/deb33889ff1aac0d542a9fd08f946461cccfc1c7/client/internal/httpsender.go#L201 
We have the backoff retry strategy for failed requests; however, underlying transport would close the request body and should be rewound for any subsequent attempt. This creates a thin wrapper around the `http.Request` that helps to rewind the body before making a request. We hijack and close the underlying connection to simulate the connection error case.

Rewind the request body for retries

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/internal/clientcommon.go
client/wsclient.go
internal/examples/agent/agent/agent.go
internal/examples/server/certman/certman.go
internal/examples/server/data/agent.go
internal/examples/server/uisrv/ui.go

- Implemented spec change https://github.com/open-telemetry/opamp-spec/pull/162
- Added ability for the client to request connection settings.
- Added CSR flow example to demonstrate the new capability.

Add support for client-initiated connection settings request

---

server/callbacks.go
server/server.go
server/serverimpl.go

Add doc comments to server API.

chore: add doc comments to server API

---

server/server.go
server/serverimpl.go
server/serverimpl_test.go

Add an `Addr()` method to fetch the network address Server is listening on. I think this may be useful for the supervisor to start a server with 0 port to allocate an ephemeral port and get the allocated port for rendering an agent config.

feat: allow to get the network address server is listening on

---

client/internal/receivedprocessor.go

Fixing error throw logger when setting invalid instance UID provided by the server.

Fix set invalid instance UID error throw

---

go.mod
go.sum
internal/examples/go.mod
internal/examples/go.sum

Replaces https://github.com/open-telemetry/opamp-go/pull/222
Adds `go mod tidy` on top of it to make sure it build.

fix(deps): update module github.com/cenkalti/backoff/v4 to v4.2.1

---

renovate.json

See https://docs.renovatebot.com/golang/#module-tidying

Make renovatebot to run go mod tidy

---

go.mod
go.sum
internal/examples/go.mod
internal/examples/go.sum

[Replaces #229](https://github.com/open-telemetry/opamp-go/pull/235)

fix(deps): update module google.golang.org/protobuf to v1.32.0

---

client/clientimpl_test.go
client/internal/httpsender.go
client/internal/httpsender_test.go
client/internal/receivedprocessor.go
client/internal/wsreceiver_test.go
client/types/callbacks.go
client/wsclient.go
client/wsclient_test.go
internal/examples/agent/agent/agent.go
internal/examples/supervisor/supervisor/supervisor.go

This is a follow up to #237 and #247, adding context propagation for client methods. 
**This involves a breaking change for the client interfaces**

Add client context propagation

---

client/wsclient.go
client/wsclient_test.go
internal/retryafter.go

This commit allows the opamp client to follow redirects after websocket handshake failures. Redirect following is not implemented by gorilla/websocket, but can be handled by inspecting the returned response object for 3xx status and Location header.
Closes #250

Follow HTTP redirects after failed WS dials

---

.github/workflows/static-check.yml
client/httpclient_test.go
client/internal/httpsender.go
client/internal/mockserver.go
client/internal/packagessyncer.go
client/wsclient.go
internal/certs.go
internal/retryafter_test.go
internal/wsmessage.go
protobufshelpers/anyvaluehelpers.go
server/serverimpl_test.go

This commit adds staticcheck as a github action and resolves existing issues flagged by staticcheck. I've grouped the issues into individual commits so that they can be considered independently. Most of the issues are deprecated uses of stdlib, unused errors, and ineffective branches or statements. But, there is one stylistic issue too that is more subjective.
staticcheck is a very conservative linter that has a focus on minimizing false positives. I've found that staticcheck has improved the quality of my own work, and has also made pull requests easier to evaluate.
Each issue is tagged with an identifier that can be consulted here: https://staticcheck.dev/docs/checks/

Add staticcheck github action, resolve existing lint

---

client/internal/receivedprocessor.go
client/types/callbacks.go

Contributes to https://github.com/open-telemetry/opamp-go/issues/261
I intentionally left undefined the blocking vs nonblocking requirement for the callback. I suggest that we refine this after we make implementations and settle on a particular behavior.
A continuation of this PR is needed that implements steps 4 and 5 of the flow described here:
https://github.com/open-telemetry/opamp-go/issues/261

Remove OnOpampConnectionSettingsAccepted callback

---

client/internal/wsreceiver.go
client/internal/wsreceiver_test.go
client/internal/wssender.go
client/wsclient.go
client/wsclient_test.go

Gracefully shutdown of the websocket client

---

README.md

I've not had time or bandwidth to follow the work in this repo.

move codeboten to emeritus approver

---

client/clientimpl_test.go

The test sometimes fails on my machine. The EventuallyExpect function needs a condition that returns false instead of failing when the expected message is not received, since a different message may be sent by the client.
This fixes the test. I run it 100 times and it passes: `go test -run TestOfferUpdatedVersion/ws -v -race -count 100`
(Apologies for whitespace changes, but they appear to be incorrectly formatted, my editor autoformatted it and `go fmt` passes on the text).

Fix test TestOfferUpdatedVersion

---

internal/tools/tools.go

The Go wiki on GitHub has moved to go.dev. This PR updates a comment to link to its new place.

docs: fix broken link

---

client/internal/clientstate.go

This section was removed when the StatusReport fields were moved over to AgentToServer on https://github.com/open-telemetry/opamp-spec/commit/bc9c8ba8f3281bf924449bd54a13742c683f5639
This PR updates the docstring for a newly added field and links back to the status reporting section of the spec.

docs: fix ClientSyncedState docstring with a valid link

---

internal/retryafter.go
internal/retryafter_test.go

The initial implementation of this PR attempted to fix the TestExtractRetryAfterHeaderHttpDate test by making sure the test duration was in the future. After the comment by Tigran I've pivoted to fix the parsing logic instead.
This PR amends the `parseHTTPDate` and `parseDelaySeconds` helpers to not return an error if the parsed duration is in the past; instead they now return a zero duration and nil error to trigger immediate polling.
In the current logic and the two places ([1](https://github.com/open-telemetry/opamp-go/blob/0fd73cc08a56ae911c196b6cb17bdd917e919009/client/internal/httpsender.go#L185), [2](https://github.com/open-telemetry/opamp-go/blob/0fd73cc08a56ae911c196b6cb17bdd917e919009/client/wsclient.go#L201)) it's being used, it looks that in the case that a negative seconds or …

Amend Retry-After parsing logic for negative durations

---

client/client.go
client/clientimpl_test.go
client/httpclient.go
client/internal/clientcommon.go
client/internal/clientstate.go
client/internal/httpsender_test.go
client/internal/receivedprocessor.go
client/wsclient.go

Updates #198 
This PR adds a new method to the OpAMPClient that allows clients to set their own flags (such as `RequestInstanceUid`).
This new method deviates a little bit from other ones as it just sets a uint64 instead of a pointer struct field, and doesn't use the same errors and nil checks.
Thank you in advance for taking and look, and please let me know if I'm missing anything! 🙌

Enable clients to set flags

---

client/clientimpl_test.go

I'm not _entirely_ sure this is the correct way to test this, so any feedback is appreciated cc @andykellr 
The flake is easy to reproduce currently with `go test -run=TestSendCustomMessagePendingError -count=1000 -race` .
After this fix, I've given it >25k runs and didn't manage to get any failures at all.
The flakiness in `TestSendCustomMessagePendingError` was due to the fact that the second call to `SendCustomMessage` was often not fast enough to trigger the condition, giving the first call to c.sender.ScheduleSend() enough time for a message to be sent and clearing the previous CustomMessage from the sender's first queued message in the process.
Without going deeper to add explicit synchronization, I think that delaying the start to the server can guarantee that no messages are sent …

Fix flaky TestSendCustomMessagePendingError

---

client/httpclient.go
client/internal/clientcommon.go
client/internal/httpsender.go
client/internal/httpsender_test.go
client/internal/inmempackagestore.go
client/internal/packagessyncer.go
client/internal/receivedprocessor.go
client/internal/wsreceiver.go
client/internal/wsreceiver_test.go
client/wsclient.go

This PR revives work done in previous PRs (#118, #120) to make sure that only a single package syncing operation is ever in flight and also adds a test.
The previous PRs did not account for needing to also protect `initStatuses` and `SetPackageStatuses`, so that's why the Lock and Unlock statements are not just paired in doSync. If you think the intent would be clearer using a sync.WaitGroup, let me know.
The new test makes sure that the mutex correctly protects the local storage; if we comment out the calls to Lock/Unlock and run the test with the `-race` flag we can see the race condition taking place
<details>
```
$ go test -run=TestPackageUpdatesInParallel -v -race -count=1
=== RUN   TestPackageUpdatesInParallel
==================
WARNING: DATA RACE
Write at 0x00c00003cdb0 by …
```

Limit to single inflight package syncing operation

---

client/clientimpl_test.go
client/httpclient.go
client/internal/httpsender.go
client/types/startsettings.go
client/wsclient.go

Adds a new HeaderFunc to the StartSettings that allows for dynamically editing the headers before each HTTP request made by the OpAMP library.
Closes #297

Add HeaderFunc to allow modifying headers before every request

---

client/clientimpl_test.go
client/internal/inmempackagestore.go
client/internal/packagessyncer.go
client/types/packagessyncer.go

Passes the signature field to UpdateContent, so the implementation may verify the signature of the file.
Closes #300

Add signature to UpdateContent

---

internal/examples/agent/agent/metricreporter.go

opts is created but never used.  It's necessary to pass opts the otlpmetrichttp.New() so that the configured destinationEnpoint is correctly used.

Pass opts to otlpmetrichttp.New()

---

client/httpclient_test.go
client/internal/clientcommon.go
client/internal/wssender.go
client/internal/wssender_test.go
client/types/startsettings.go
client/wsclient_test.go

Add a `HeartbeatIntervalSecond` option to `StartSettings` to allow setting initial heartbeat interval.
resolve #303

Allow setting initial heartbeat interval

---

.github/workflows/build-and-test.yml
.github/workflows/static-check.yml
go.mod
internal/examples/go.mod
internal/examples/go.sum
internal/tools/go.mod

The tooling seems to be unhappy with 1.20, e.g.
https://github.com/open-telemetry/opamp-go/pull/302
Updating to latest-1, which also matches what Collector uses: https://github.com/open-telemetry/opentelemetry-collector/blob/2d9d376ee26920d02fdb232e184dc3b1f064fc4b/go.mod#L11

Update minimum go version to 1.22

---

.github/workflows/build-and-test.yml
.github/workflows/static-check.yml
.github/workflows/tidy.yml
makefile

Fixes https://github.com/open-telemetry/opamp-go/issues/276
Verified here: https://github.com/srikanthccv/opamp-go/pull/11. You can notice that the build-and-test passes https://github.com/srikanthccv/opamp-go/actions/runs/11635165811/job/32403942593?pr=11
GitHub workflow won't be triggered from workflow https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow. Updated the types on pull_request to accept the `labeled`. We can re-trigger the workflow using label.

Add workflow to run go mod tidy on renovatebot PRs

---

.github/workflows/static-check.yml

Fixes #314 
The current staticcheck GitHub action doesn't support directory exclusions. I've implemented a matrix directory approach to fix issue #314. However, I suggest we move away from the staticcheck action entirely and create a new golang-lint CI action (taking inspiration from collector repo ci setup) instead. If that sounds good, I will create a separate PR(s) for the proposed change. Let me know what you think.

Do not run staticcheck on generated protobufs

---

client/clientimpl_test.go
client/internal/clientcommon.go
client/internal/httpsender_test.go
client/internal/receivedprocessor.go
client/internal/wsreceiver_test.go
client/types/callbacks.go
client/wsclient.go
client/wsclient_test.go
internal/examples/agent/agent/agent.go
internal/examples/supervisor/supervisor/supervisor.go

The interface has the following downsides:
- Impossible to define non-trivial default behavior. Here is an example where it was needed: https://github.com/open-telemetry/opamp-go/pull/269#discussion_r1874634261
- Adding new callbacks requires expanding the interface, which is a breaking change for existing client users.
Getting rid of the interface and keeping just a struct for callbacks solves both problems:
- Arbitrarily complex default behavior can be now defined on the struct if the user does not provide the particular callback func.
- Adding new callback funcs is not a breaking change, existing users won't be affected.

Breaking: Replace Callbacks interface by Callbacks struct

---

client/types/callbacks.go

Now that types.Callbacks is a struct and not an interface, its docs need adjusting so that the struct doesn't claim to be an interface.

chore: adjust docs for types.Callbacks

---

client/httpclient_test.go
client/internal/httpsender.go
client/types/callbacks.go
client/wsclient.go
client/wsclient_test.go
go.mod
go.sum

This commit adds a CheckRedirect callback that opamp-go will call before
following a redirect from the server it's trying to connect to. Like in
net/http, CheckRedirect can be used to observe the request chain that
the client is taking while attempting to make a connection.
The user can optionally terminate redirect following by returning an
error from CheckRedirect.
Unlike in net/http, the via parameter for CheckRedirect is a slice of
responses. Since the user would have no other way to access these in the
context of opamp-go, CheckRedirect makes them available so that users
can know exactly what status codes and headers are set in the response.
Another small improvement is that the error callback is no longer called
when redirecting. This should help to prevent undue error logging by …

Add CheckRedirect callback

---

server/serverimpl.go
server/serverimpl_test.go
server/types/callbacks.go

Resolves #330
This adds a new Server callback OnReadMessageError that is called when a read or deserialization error occurs.

feat: Supports callbacks when reading a message fails

---

.github/workflows/build-and-test.yml
.gitignore
client/client.go
client/clientimpl_test.go
client/internal/httpsender.go
client/internal/httpsender_test.go
client/internal/mockserver.go
client/internal/packagessyncer.go
client/internal/wsreceiver_test.go
client/wsclient_test.go
internal/certs.go
internal/examples/agent/agent/agent.go
internal/examples/agent/agent/metricreporter.go
internal/examples/server/certman/certman.go
internal/examples/server/uisrv/ui.go
internal/examples/supervisor/supervisor/healthchecker/healthchecker.go
internal/examples/supervisor/supervisor/supervisor.go
internal/examples/supervisor/supervisor/supervisor_test.go
internal/tools/go.mod
internal/tools/go.sum
internal/tools/tools.go
makefile
protobufs/anyvalue.pb.go
protobufs/opamp.pb.go
server/httpconnectioncontext.go
server/serverimpl.go

Go formatting based on Otel collector's approach: https://github.com/open-telemetry/opentelemetry-collector
The PR has been committed as:
- Add fmt go tools and refactor the corresponding make targets
- Add CI check
- Push formatted files

chore: add fmt makefile target and go tools

---

server/server.go
server/serverimpl.go
server/serverimpl_test.go

Fixes https://github.com/open-telemetry/opamp-go/issues/347

fix: wait for HTTP server serve() termination

---

README.md

Bindplane brand update

---

client/internal/httpsender_test.go
client/internal/packagessyncer.go
client/internal/packagessyncer_test.go
client/internal/receivedprocessor.go
client/internal/wsreceiver_test.go
client/types/callbacks.go
client/types/callbacks_test.go

Package Syncer uses the http.DefaultClient and gives users not chance of configuring an HTTP client for the purpose of downloading packages. This means users cannot configure TLS, timeouts, keep-alive, use a custom transport, a proxy, etc to faciliate package file downloads.
This commit add a new DownloadHTTPClient callback that allows users to provide a custom HTTP Client to use with package downloads.
The callback will be called for every DownloadableFile. This is to allow users to tweak the client based on the file URL. Users who do not need to tweak the client for each download can always return the same client. We could call the callback just once per agent and use the same client for all downloads but I felt this gives users more flexibility and makes it very clear that the client …

Add DownloadHTTPClient callback

---

server/serverimpl.go
server/serverimpl_test.go
server/wsconnection.go

Addresses this [issue](https://github.com/open-telemetry/opamp-go/issues/358) by addding an atomic.Bool so we only close the underlying websocket connection once. This PR also adds the test `TestDisconnectServerWSConnection` to ensure that that error log isn't generated when the connection is closed server-side. I renamed `TestDisconnectWSConnection` to `TestDisconnectClientWSConnection` since it tests closing the connection from the client-side, though the comments in the test implied it tested disconnecting from the server.
Perhaps it would be better to simply ignore the error when we close the connection twice? I'm unsure if there are error conditions where we'd want to be able to try to close the connection again.
Resolves https://github.com/open-telemetry/opamp-go/issues/358

fix: Add atomic.Bool to ensure wsConnection.Disconnect() is only called once

---

client/clientimpl_test.go
client/internal/mockserver.go
client/internal/wssender.go
client/wsclient.go
client/wsclient_test.go

- In the [opamp-spec document](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agenttoserveragent_disconnect), 
> AgentDisconnect MUST be set in the last AgentToServer message sent from the Client to the Server.
- But, currently there is no implementation for it.
- Because of it, the below issue occurs.
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39676
- To resolve it, ensure to send `AgentToServer.agent_disconnect` when the client's `Stop()`.
[Edit]
related to #179 
[Edit - 2]
- To ensure to send last scheduled message, when client is stopped.

fix: Send AgentToServer.agent_disconnect when client is stopped.

---

internal/wsmessage.go
server/serverimpl.go
server/serverimpl_test.go
server/types/callbacks.go
server/wsconnection.go

This PR adds functionality to the loop responsible for reading messages from the WebSocket connection to exit if we fail to send a message over the connection. This would trigger a reconnect from the client. Additionally it adds a new callback, OnMessageResponseError, that can be called in this event. This would follow behavior present when we fail to read from the connection.
Resolves https://github.com/open-telemetry/opamp-go/issues/426

feat: WebSocket server send error callback

---

client/internal/mocksender.go
client/internal/package_download_details_reporter.go
client/internal/package_download_details_reporter_test.go
client/internal/packagessyncer.go
client/internal/packagessyncer_test.go

Was running into a couple issues here while working on the supervisor to support upgrading the collector.
1. Data race
When syncing the package, we spin off a go routine to provide periodic updates on the progress. TLDR this go routine doesn't clean up by the time we update the package state with a successful install. This change adds a wait group so we make sure this routine exits before we continue.
2. Idle go routines
After resolving the data race, was also running into the following error. This was resolved by calling "CloseIdleConnections" on the http client we get to download the file. 
If you have any questions about these changes, let me know!

fix: Package Download race condition and close idle connections
